FROM golang:1.14-stretch



RUN apt-get update && apt-get install -y --no-install-recommends \
		libglib2.0-dev \ 
		curl \
		make

RUN curl -sL https://deb.nodesource.com/setup_16.x | bash - \
	&& apt-get install -y nodejs \
	&& curl -L https://www.npmjs.com/install.sh | sh

# ENV PATH="/usr/local/go/bin:${PATH}"

VOLUME /var/app
WORKDIR /var/app

CMD ["/bin/bash"]
