FROM golang:1.16-stretch

ENV CGO_LDFLAGS_ALLOW=-fopenmp
ENV GO111MODULE=on


RUN apt-get update > /dev/null && apt-get install -y libglib2.0-dev curl make > /dev/null


VOLUME /var/app
WORKDIR /var/app

CMD ["/bin/bash"]
